### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by adamdahan** [onmyway133/EasyConfetti#15]
If somebody uses the .image you shouldn't assume that they want the particles to be generated with color - ruins the effect.

Just a heads up - thanks for the code :)

**Comment by samsoncsyu7777** [comment]
Hi,
I want to use "customize" in Cheers.
What is the syntax of it and how to use it?
Thanks a lot!

**Comment by onmyway133** [comment]
@samsoncsyu7777 Hei, what do you want to customize, and have you checked config https://github.com/onmyway133/Cheers#configuration ?

**Comment by samsoncsyu7777** [comment]
The size of the shapes

在 2019年4月5日週五 19:15，Khoa <notifications@github.com 寫道：

**Comment by onmyway133** [comment]
@samsoncsyu7777 Can you check that `cells` work for you with scale https://developer.apple.com/documentation/quartzcore/caemittercell/1522287-scale?language=swift ?

```
cheerView.config.customize = { cells in

}
```

**Comment by samsoncsyu7777** [comment]
Is it

cheerView.config.customize = { cells in
.scale = 20
}

?

Thanks a lot!


在 2019年4月5日週五 19:18，Khoa <notifications@github.com 寫道：
