### ISSUE TITLE
Make the latest code available in a release

### ISSUE THREAD

**Issue by ThibaultKlein** [onmyway133/EasyConfetti#16]
Hi,

Sorry if I missed something, but it appears that the release 2.0.0 doesn't contain the latest code updates that were merged in the latest PRs. 
For example, I couldn't find the code changes from [PR #9](https://github.com/hyperoslo/Cheers/pull/9).

Any chance you can publish a new version with the latest code?
Thanks!

**Comment by onmyway133** [comment]
@ThibaultKlein Hi, sorry for the delay. Can you check https://github.com/hyperoslo/Cheers/releases/tag/2.0.1

**Comment by ThibaultKlein** [comment]
No worries @onmyway133, I installed the 2.0.1 version but the new code wasn't there.

For reference this is what I'm using in my Podfile at the moment:

`pod 'Cheers', :git => 'https://github.com/hyperoslo/Cheers.git', :commit => '46fb62ff13f4fa72c36f0b285693a814de002878'`

**Comment by onmyway133** [comment]
@ThibaultKlein Hi, can you check https://github.com/hyperoslo/Cheers/releases/tag/2.0.2

**Comment by ThibaultKlein** [comment]
Thanks @onmyway133 it works now!

**Comment by onmyway133** [comment]
@ThibaultKlein cheer 🥂 🎉
