### ISSUE TITLE
How to display the animation is coming from the top from starting.

### ISSUE THREAD

**Issue by ajay2c9** [onmyway133/EasyConfetti#2]
Hi,
I'm using the pod in my project. When i start the animation with the code
 self.cheerView.start()
The animation is displaying like the view already fill with particles and showing the animation.
I want to display the animation like the  particles starts from the top and getting down like in current animation. but currently particles are displayed on the view(i.e not started from the top) continued  the animation. How to implement the animation that is starting from the top of the view.

Thank you

**Comment by onmyway133** [comment]
@ajay2c9 Hi, thanks for checking this out. We just published 1.1.0 https://github.com/hyperoslo/Cheers/releases/tag/1.1.0 which addresses this problem. Please let us know if it fixes the issue for you

**Comment by ajay2c9** [comment]
**@onmyway133** Hi, Thanks for the reply .
 In the given code the issues is fixed and thank you for the update.

**Comment by onmyway133** [comment]
@ajay2c9 🎉
