### ISSUE TITLE
Release for Swift 4.2

### ISSUE THREAD

**Issue by anderscarling** [onmyway133/EasyConfetti#22]
Hi!

Just wanted to ask/remind you to release the new version for Swift 4.2 to CocoaPods - I can see master is already patched. :)

**Comment by doctorcolinsmith** [comment]
A new release for Swift 4.2 would help me out.  I'm currently using a forked release so I can pull Cheers in to my project with Cocoapods.

**Comment by phlippieb** [comment]
Pointing Cocoapods to the patched commit (https://github.com/onmyway133/Cheers/commit/1429d87a17ab0dee9fd31e0e424ac7104855169d) as a workaround:
```
pod 'Cheers', :git => "https://github.com/onmyway133/Cheers", :commit => "1429d87"
```

**Comment by onmyway133** [comment]
@anderscarling @doctorcolinsmith @phlippieb Sorry that it took long time, you may have forgotten this by now, but I just make a new release with Swift 4.2 https://github.com/onmyway133/Cheers/releases/tag/2.2.0 yay 🎉

**Comment by anderscarling** [comment]
Great! Thanks!
