### ISSUE TITLE
Confetti falling down from top left of view

### ISSUE THREAD

**Issue by peterwarbo** [onmyway133/EasyConfetti#23]
Hi,
Not sure if I'm doing anything wrong but I add the view and use auto layout to constrain it to the edges of my superview but for some reason the confetti is not sprinkled from the top of the view (like illustrated in the readme) but from the top left corner. Why is that?

**Comment by kostyleteam** [comment]
Add in init 
```cheerView.frame = view.bounds```
So your initialization will look like 
```
  let cheerView = CheerView()
  cheerView.frame = view.bounds
  view.addSubview(cheerView)

**Comment by rcelikkaya** [comment]
I am looking for same issue .Thanks a lot.
