### ISSUE TITLE
Does not always work

### ISSUE THREAD

**Issue by phlippieb** [onmyway133/EasyConfetti#25]
For my use case, I want to add this effect to a view controller just after it has been pushed to a navigation stack. Strangely, sometimes when the VC is pushed, the confetti effect is not shown at all.

I created an [example project](https://github.com/phlippieb/CheersTest) that demonstrates the issue. To see it in action:

1. Clone or download the project
2. `pod install`
3. Run the project in Xcode

The example app has a 'continue' button in the centre of the screen. Tapping it will navigate to a new screen with the confetti effect enabled. After going back and forth between the two screens a few times, the effect will randomly fail to display.

**Comment by thedore17** [comment]
Same here. A lot of times CheerView doesn't start on start. Any workarounds?

**Comment by onmyway133** [comment]
@phlippieb Hi, if you call `start` method as part of button touch action or delay a bit using DispatchQueue, does that work?

**Comment by phlippieb** [comment]
@onmyway133 I've added a delay around start (using `DispatchQueue.main.asyncAfter(.now() + 10)`). It had no effect; the confetti still fails to start sometimes, and often on the first time. 

My use case is that the confetti should start automatically once a screen becomes visible, so testing with a button doesn't interest me (nor does waiting 10 seconds but it was easy to test 🙂 ).

The example project I included is extremely simple and only uses your library as a pod, so it should give you everything you need to debug the issue.

**Comment by jbuckner** [comment]
I was also running into this issue and did some digging into it. It turns out you have to set the `beginTime` on the `CAEmitterCell`s instead of the `CAEmitterLayer`. I opened #27 to fix.

**Comment by onmyway133** [comment]
@phlippieb The PR from @jbuckner was merged, can you check master branch to see if it works for you?

**Comment by phlippieb** [comment]
@onmyway133 I can confirm that the fix works 🎉

**Comment by onmyway133** [comment]
@phlippieb cool, I will make new release soon

**Comment by onmyway133** [comment]
New release is out https://github.com/onmyway133/Cheers/releases/tag/2.3.0, thanks a lot for contributing @phlippieb @jbuckner ❤️
