### ISSUE TITLE
Type 'CAEmitterLayerEmitterShape' (aka 'NSString') has no member 'line'

### ISSUE THREAD

**Issue by MalcolmnDEV** [onmyway133/EasyConfetti#26]
Type 'CAEmitterLayerEmitterShape' (aka 'NSString') has no member 'line'
Type 'CAEmitterLayerRenderMode' (aka 'NSString') has no member 'additive'

**Comment by MalcolmnDEV** [comment]
Seems to only be an issue in the latest release

**Comment by onmyway133** [comment]
@MalcolmnDEV Do you use swift 4.2 ?

**Comment by MalcolmnDEV** [comment]
my Xcode Swift Language Version is set to 4 ..... does it have to be set to 4.2?

**Comment by thedore17** [comment]
Same issue. Any resolution?

**Comment by anuranBarman** [comment]
I hope you are getting two errors there for line and additive. replace them with `kCAEmitterLayerLine` and `kCAEmitterLayerAdditive`.
final code:
```swift
emitter.emitterShape = kCAEmitterLayerLine
emitter.renderMode = kCAEmitterLayerAdditive
```

**Comment by onmyway133** [comment]
@MalcolmnDEV @thedore17 You need swift 4.2 for the latest Cheers version

**Comment by thedore17** [comment]
Thanks! I updated my code to 4.2 and it works now. However, it doesn't always start when commanded to. Sometimes starting just does nothing. Sometimes it works.

**Comment by onmyway133** [comment]
@thedore17 so it may relate to this https://github.com/onmyway133/Cheers/issues/25, let's discuss it there. I will take a look soon.
