### ISSUE TITLE
How to implement animation like first few particles next more particles and at the end only few particles are getting down.

### ISSUE THREAD

**Issue by ajay2c9** [onmyway133/EasyConfetti#3]
Hi,
I am using Cheers pod in my app . I have a requirement to display the animation like below.
First few particles are coming later more and at the end only few are getting down like in the below video .
 https://videohive.net/item/confetti/19479197?s_rank=7

Please give suggestion to implement the above requirement.
Thank you

**Comment by onmyway133** [comment]
Hi, currently `Cheers` is designed to work with this confetti animation style. If you want customised effects, you can configure it in https://github.com/hyperoslo/Cheers/blob/master/Sources/Config.swift#L31 to your liking
