### ISSUE TITLE
How to implement the animation of the particles spinning vertically and getting down.

### ISSUE THREAD

**Issue by ajay2c9** [onmyway133/EasyConfetti#4]
Hi,
I am using Cheers pod in my app . I have a requirement to display the animation like below video.

https://videohive.net/item/confetti/19479197?s_rank=7

In this video the white sprinkle particles are vertically spinning and getting down  (time:0.04sec). 

Plz give suggestions to implement that vertically spinning animation 

Thank you

**Comment by onmyway133** [comment]
@ajay2c9 Hi, currently `Cheers` is designed to work with this confetti animation style. If you want customised effects, you can configure it in https://github.com/hyperoslo/Cheers/blob/master/Sources/Config.swift#L31 to your liking
