### ISSUE TITLE
Emitting from the top left of programmatic super view

### ISSUE THREAD

**Issue by ritvikupadhyaya** [onmyway133/EasyConfetti#6]
Hi, I used the library to have confetti start from the top across the entire width of the screen like shown in the README animation. However, my usage was slightly different. In place of adding the confetti on the `ViewController`'s view, I added to a different view that is rendered on top of the `ViewController`. Think an alert controller's background. Since my new view was created programmatically, the bounds were 0,0,0,0. A better way to make it work for all superviews that may or may not be rendered before the view is added to the subview.
I have already fixed it for myself, without breaking the existing functionality. Opening up the PR for you to review it!

**Comment by ritvikupadhyaya** [comment]
PR for the feature: https://github.com/hyperoslo/Cheers/pull/7

**Comment by onmyway133** [comment]
@ritvikupadhyaya Hi, thanks for the PR. The idea of `Cheers` was to make particle effect within its own view, without knowing about the parent. I think the better solution to this, is to able to configure `CAEmitterLayer` via `config property`

**Comment by ritvikupadhyaya** [comment]
Okay that makes sense if that was what was kept in mind while designing the repo!
